// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOSWfZCoEJG1AXV0VdKF4DGCW9ruj9W98',
    appId: '1:755114812620:web:3fef2bfcf5ae7c6ae8ce69',
    messagingSenderId: '755114812620',
    projectId: 'captone1-3fba1',
    authDomain: 'captone1-3fba1.firebaseapp.com',
    storageBucket: 'captone1-3fba1.appspot.com',
    measurementId: 'G-YJZHT03DX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFLewpr6VKFXhgJ9Q1hOx4LcT3_XHgq8A',
    appId: '1:755114812620:android:23237335674d216fe8ce69',
    messagingSenderId: '755114812620',
    projectId: 'captone1-3fba1',
    storageBucket: 'captone1-3fba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe3U8E_OoYp2KaOwNfBH9JfbO8ofdkJ6Q',
    appId: '1:755114812620:ios:8d04a8609e22f781e8ce69',
    messagingSenderId: '755114812620',
    projectId: 'captone1-3fba1',
    storageBucket: 'captone1-3fba1.appspot.com',
    iosClientId: '755114812620-ot7e9ijfi5djev32nv6bbsd8dks84dfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.captoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe3U8E_OoYp2KaOwNfBH9JfbO8ofdkJ6Q',
    appId: '1:755114812620:ios:4f19dbc21512b61ce8ce69',
    messagingSenderId: '755114812620',
    projectId: 'captone1-3fba1',
    storageBucket: 'captone1-3fba1.appspot.com',
    iosClientId: '755114812620-ru965su7kb2ides2ls5b1tjbm80l0031.apps.googleusercontent.com',
    iosBundleId: 'com.example.captoneApp.RunnerTests',
  );
}
